### ISSUE TITLE
Add a simple toggle to disable autorefresh

### ISSUE THREAD

**Issue by jvoisin** [airsonic/airsonic#1003]
It would be nice to be able to easily disable autorefresh temporarily.

**Comment by jooola** [comment]
Great idea, I would even add a way to disable autorefresh if browser tab isn't focused.

**Comment by fxthomas** [comment]
There's a "Delay when reloading the album list" option in the personal preferences, although it's maybe too hidden for what you have in mind.

**Comment by jvoisin** [comment]
My usecase is that when I'm using the `random` view, I'm looking at my albums, and suddenly, they're changing, damn! Or, when using the `latest` view, the page is refreshing, for no reason at all (it should only refresh if a scan just finished for example).

**Comment by eharris** [comment]
Personally, I don't really understand what motivated there being an auto-refresh at all, and would be perfectly happy if that setting and capability was just removed entirely.  I don't see any reason to ever want a page of content or my position in the page to "automatically" change out from under me, and anyone that does can specifically refresh the page.  And speaking as a server admin, I don't want users being able to trivially cause constant (and IMO pointless) traffic to my server just because they might have left a tab open somewhere.

Note: #1179 is somewhat related.

**Comment by jvoisin** [comment]
I like the autorefresh on the "Random album" page, but I guess than a simple "refresh" button there would do the job just fine.

**Comment by eharris** [comment]
There's already a "> More" link at the top and the bottom of the page, and the link just does a refresh.  That should probably be changed to a refresh icon and "Refresh".

**Comment by eharris** [comment]
#1338 added to change the random page "More" to "Refresh" with icon.
#1339 added to remove the auto-refresh feature.
