### ISSUE TITLE
Discord for Airsonic?

### ISSUE THREAD

**Issue by riahc3** [airsonic/airsonic#1087]
Any plans to make a Discord for Airsonic?

**Comment by jvoisin** [comment]
We already have a [matrix channel]( https://matrix.to/#/#airsonic:matrix.org ) and an [irc chan]( http://webchat.freenode.net/?channels=%23airsonic ). We don't have plans currently to add a discord one, but feel free to open open, and to bridge it with on of the others, since they are already bridged to each other, although I don't think this it'll be super-useful to have yet-another communication channel.
