### ISSUE TITLE
Search result quality

### ISSUE THREAD

**Issue by CTParkinson** [airsonic/airsonic#1142]
## Problem description

Had the same issue with Subsonic, Searching is kinda garbage.
For example searching for "For all The Cows" - by Foo Fighters.
![image](https://user-images.githubusercontent.com/46909431/59967001-49b91500-951c-11e9-8607-2e47c41a0e49.png)

Why does a full text match not appear above everything else?

But worse than that, the artist name gets matched in song and album results, and also the album titles get matched in song results;
![image](https://user-images.githubusercontent.com/46909431/59967077-46725900-951d-11e9-8754-9394c2f97211.png)

literally every song by Lamb of God is listed, in the order they appear on the album, and i assume each album too, because the search term matches the artist name but not the song titles...

Since the artist results lists them already, unless the album contains the search term also I would expect to not see any results matching the band name in albums, same goes for song results.

Unless the item title matches the search, maybe don't show that in the results set?

### Steps to reproduce

1. Search for practically anything.

## System information

 * **Airsonic version**: 10.2.1-RELEASE – February 18, 2019
 * **Operating system**: Whatever DietPi is. Debian? Unsure which version.
 * **Java version**: I don't know
 * **Proxy server**: None

## Additional notes

I would like to use the search via the API, images were taken from Airsonic ui for familiarity

**Comment by tesshucom** [comment]
Unfortunately, current search queries are not optimized for scoring.

> Searching is kinda garbage.

I think you should be very careful not to break past functions, but search functions are functions that need to be improved because they are considered to contain certain problems and potential bugs.
I think so too.


> Unless the item title matches the search, maybe don't show that in the results set?

That is also a strong valid solution, but the Artist displayed in the Songs line is the tag data of the song, so the content may differ from the Album Artist.

Therefore, in general, the method of adjusting the Boost value is taken.
The Boost value defaults to 1.
(For example, designate as in Song1.3 Album1.2 Artist1.1.)
That way you can't avoid a complete search, but you can increase the match score of the song title and show it on top.
(``Sorting`` is a slightly different concept.)

The current search feature includes adjustment of the Boost value, but is a dead code.
We need to improve this.

I have created a PR on #1130.
This is itself a prerequisite PR for search engine updates.
But I think it is also the first step in tackling these various search qualities.

For example, we are looking into enabling registration of multiple Boost values ​​for the index.
[IndexType](https://github.com/airsonic/airsonic/blob/b31e97db19b1fff2f9aa19e880a110362fe0a2fe/airsonic-main/src/main/java/org/airsonic/player/service/search/IndexType.java)
The current implementation only allows boost values ​​to be set for one field, and is dead code.

**Comment by glennguy** [comment]
@CTParkinson I've had the same issue as you. 

I get the exact problem with any search containing 'the' - Dream **The**ater is returned in the results. I use DSub as a client and any Android Auto search to "play artist The [band name]" would start playing Dream Theater. "The" is in the default list of stop words and results containing the word "the" are removed, but the partial match in "Theater" is used.

I modified a few things in SearchService with some success

A combination of 2 things were needed:

* Changing the operator on search terms to `AND`. (`queryParser.setDefaultOperator(QueryParser.Operator.AND)`)
* Removing the default stop words list from the search analyzer ('the, is, and, I etc.) I can see why a standard search engine would want to avoid these words but for music we should use them.

Now a multi word search will only show results containing all words - you should get your 1 song result of "For all the cows" and 0 for album/artist

@tesshucom I don't know how this applies to the updated Lucene version however I thought it worth considering. Perhaps even have this option behind a setting, although the database needs reindexing with the change so it's not something you'd want to change on a search by search basis.

**Comment by tesshucom** [comment]
There is a test case in [AnalyzerFactoryTestCase](https://github.com/airsonic/airsonic/blob/1c4a6aada5aab0015edb1eb0dc18444a57936174/airsonic-main/src/test/java/org/airsonic/player/service/search/AnalyzerFactoryTestCase.java)#Stopward.
It is appropriate for stop words to correspond with filters rather than operands.

Stopword is used to improve accuracy and reduce index size, except for words that become noise when searching general documents.
The STOP_WORD employed by Airsonic are currently deprecated because of over-deletion of words.
A new feature called ENGLISH_STOP_WORD has been newly added.
Of course, it is necessary to discuss whether it is suitable for music search different from general document search such as newspaper and mail.

It may be better to take into account that the current design was limited by the machine resources at the time.
There may be some problems, but it wasn't bad at the time. . .

After the update, specification changes that may cause an increase in the index may be relatively acceptable.
The storage size will be very small as the index storage method changes.

Anyway, I think that the specs that seem controversial need to be visualized in the form of additional test cases.

**Comment by glennguy** [comment]
I can see you've been thinking about this a lot! :)

With regards to stop words, is it possible to ignore them completely on the search input? No tokens, as if they were never part of the search?

**Comment by tesshucom** [comment]
Oh, maybe I was confused.

- Divided into words with Tokenizer
- Delimited words included in Stopward are excluded

So, ``the`` is completely ignored.

Airsonic should not hit ``dream theater`` with only ``the`` input.

On the other hand, some clients, such as MusicBee plugin, download object data locally beforehand and do local search instead of API search.
In these cases it is the client's responsibility even if the desired search results are not obtained.

I do not know the specifications of DSub.
If the search results from the Airsonic web screen are different from the client's results, you should suspect the client's implementation.

**Comment by glennguy** [comment]
Thanks for the insight! I've only poked around not knowing anything apart from some quick reading of the Lucene docs, good to know it's a bug and not intended behavior!

Another issue that I've noticed in the current version is (and this is similar but not the same as OP's) is the search scoring:
![Capture](https://user-images.githubusercontent.com/11909320/60227640-73cf5600-98d3-11e9-80fb-aef6577389da.JPG)

In this search you would hope/expect the song "Only" to be at the top of the list as the search query is 100% of the match, then perhaps followed by "Only One".

**Comment by tesshucom** [comment]
It is possible, and I think that all the functions that the user generally wants are included in Lucene's functions.

Reporting problems and bugs is very useful.
Therefore, it is recommended to report each one separately.

The maintainers of Airsonic specification will label it easier.
As a result, problems are likely to be dealt with at the right time.

**Comment by glennguy** [comment]
@tesshucom  sure thing, I'm just posting this here because I think the issue is the same, I've just provided another example that might help to narrow down or point out what's behind it.

Thanks heaps for your helpful insight and contributions to help improve the searching!

**Comment by tesshucom** [comment]
I think the user is asking for something like this.
If you enter ``will``:

![image](https://user-images.githubusercontent.com/27724847/60358024-273d6500-9a10-11e9-9728-8e65adfb2b1c.png)

This is my local experiment, but I have made some adjustments.

 - Adjustment of Stopward (``will`` usually be excluded from search)
 - Adjustment of scoring (reflect the match rate, Song name priority)

If this doesn't work, there is a way to force the score up by adding an exact match query in addition to the forward match too.
(To avoid the situation where ``williams`` can not be found.)

The problem is that the current implementation is in a situation where it is difficult to make corrections, even if the solution is known.

In addition to search engine update tasks, I do design split and test addition though it is roundabout.
If things go well, it will be easier to improve the search function.

**Comment by tesshucom** [comment]
@fxthomas
This issue has been resolved and can be closed.
It is hoped that new topics will be added and necessary adjustments will be made as new mis-search related issues occur.

**Comment by fxthomas** [comment]
Great, thank you very much for keeping track of this!
