### ISSUE TITLE
Playlist Subsonic Apps

### ISSUE THREAD

**Issue by screwfaze** [airsonic/airsonic#1268]
## Problem description

Please implement a feature to allow rearranging playlists on the android mobile apps for subsonic.

### Steps to reproduce

Does not currently exist.

## System information

 * **Airsonic version**: 10.4.0-RELEASE – July 13, 2019
 * **Operating system**: Docker
 * **Java version**: Apache Tomcat/8.5.42, java 1.8.0_222, Linux (219.9 MB / 387.0 MB)
 * **Proxy server**: None
 * **Client**: Dsub

## Additional notes

The only thing currently missing from Airsonic in my opinion is the ability to rearrange playlist items from the subsonic apps available. Would be perfect if you didn't have to login to a browser every time you want to change the order of your playlist. I am always using the dsub app on the move listening to playlists and would really love to be able to update my playlists without having to login to my pc to do this.

Thanks

**Comment by eharris** [comment]
The Airsonic/Subsonic API already provides the `updatePlaylist` endpoint which allows removing and adding songs to an existing playlist.  While the API only currently allows appending new songs to the playlist (not inserting in the middle), inserting can still effectively be performed by deleting all songs after the intended insertion point, adding the song you want there, and then adding back the songs that should be after it.

Since this capability already exists in the API, you should raise this issue with the client apps you are using to implement this feature.

**Comment by screwfaze** [comment]
Sorry mate but that is not really how playlists should work, you should be able to rearrange playlists without having to delete songs. Imagine you have 200 songs and you want to change the 3rd one, are you going to delete your whole playlist and start again?

**Comment by eharris** [comment]
I'm not saying you should have to do that manually, the client app can and should do that for you.
