### ISSUE TITLE
That top navigation restyling... :-\

### ISSUE THREAD

**Issue by nx6** [airsonic/airsonic#1424]
## Problem description

This is kinda a nitpicky issue, I apologize.

Theme: 2 Minutes to Midnight

**10.2.1:**
![Top navigation on version 10.2.1](https://i.imgur.com/8izWzot.png)

**Later versions:**
![Top navigation on current Airsonic](https://i.imgur.com/EnbnFKD.png)

I'm not sure who thought this change was better, but aesthetically speaking, it's certainly not. Having all this text boldfaced only makes it more noticeable that the font size of all three lines is fairly similar and gives it a rather "clunky" appearance. Also, notice how much longer the category row is now. This text does not wrap around in any way, so now categories that were usable before ("By decade" / "By genre" / "All") are more likely to get pushed off the edge of the window, out of reach, depending on the browser window size.

### Steps to reproduce

This is a general appearance comment, not really a playback functionality issue.

## System information

 * **Airsonic version**: 10.5.0-RELEASE
 * **Operating system**: FreeBSD 11.2-RELEASE-p9
 * **Java version**: Apache Tomcat/8.5.43, java 1.8.0_192,
 * **Proxy server**: nginx 1.16.1
 * **Client**: *n/a -- seen in Waterfox, Chrome, and Safari*
 * **Language**: en-US

## Additional notes

Is the styling here part of the theme? If I can just edit a theme file myself and make things as I want here I'd be fine with that. Considering this change is appearing on all themes I've tried I assume it's not.

**Comment by randomnicode** [comment]
Your issue is because of this here:
https://github.com/airsonic/airsonic/blob/master/airsonic-main/src/main/webapp/WEB-INF/jsp/home.jsp#L41

These links are rendered emboldened because they are headings (h1, h2).

It's not really part of the theme, but part of the html content itself. You could:
- Change the content: Remove the h1 and h2 tags (make them into divs or spans or something), or
- Change the presentation: Tell your css to not embolden this class. Here is the operative portion of a css file controlling this thing's presentation (for one view at least): https://github.com/airsonic/airsonic/blob/master/airsonic-main/src/main/webapp/style/default-without-mediaelement.css#L350-L354
Add `font-weight: normal;`or something to the class

Need to recompile in both scenarios.

I suspect the latter was the operative change between 10.2 and later. No idea if someone wants to take this up.

**Comment by fxthomas** [comment]
Maybe look into https://github.com/airsonic/airsonic/pull/922?
