### ISSUE TITLE
Search results are not cleaned up without restart

### ISSUE THREAD

**Issue by di72nn** [airsonic/airsonic#1437]
## Problem description

Removed files are searchable until airsonic restart.
If I rename files/folders and run clean&rescan, the old files are still present in the search results. The stats at the bottom of the left panel are updated correctly. Search results go back to normal after airsonic restart. I only noticed it a couple of days ago, but it probably started to happen with `10.5.0`.
I didn't notice anything unusual in the logs (with the default log level).

There's a couple of similar issues open, but they seem to cover somewhat different problems.

### Steps to reproduce

1. Move/rename files or folders.
2. Run "Clean-up database", "Scan media folders now", wait for it to finish.
3. Search for the old filenames.
4. Search shows old non-existent files (along with the new ones, if they match the query).

## System information

 * **Airsonic version**: 10.5.0
 * **Operating system**: Arch Linux
 * **Java version**: 8
 * **Proxy server**: nginx
 * **Client**: Firefox
 * **Language**: English

Thank you for developing airsonic, I find it very useful!

**Comment by tesshucom** [comment]
The phenomenon is a search result but there seems to be a problem with the earlier process.
Because it will be healthy on reboot.

 - Lucene seems to work fine. Unit testing has been added by #1264 . Unit tests have confirmed that Lucene index deletion and Searcher refreshing work correctly. Unless degrated.

 - Probably not cache.
The cache is false in ㏈ access after Lucene search (addIgnore performed by Util). Also, if the cache is defective, #1264 is not established.

It may be related to #1425 pointed out by @fxthomas ... ?

There is a difference between whether or not it still exists in the file system, but there seems to be a case where this judgment is not successful.
DB (or file system) judgment processing.

**Comment by tesshucom** [comment]
- Lucene seems to work fine ...? Unit testing has been added by #1264 . Unit tests have confirmed that Lucene index deletion and Searcher refreshing work correctly. Unless it deteriorates, it seems to work normally by itself.

 - Probably not cache.
The cache is false in ㏈ access after Lucene search (addIgnore performed by Util). Also, if the cache is defective, #1264 is not established.

It may be related to #1425 pointed out by @fxthomas ... ?

There is a difference between whether or not it still exists in the file system, but there seems to be a case where this judgment is not successful.
DB (or file system) judgment processing.

**Comment by fxthomas** [comment]
Yup, Airsonic is somewhat weak to renaming/moving media files around, we have a few failure cases that occur from time to time...

I don't think it is related by #1425 because it clears up after restart - so the database is in a good state, presumably.

@tesshucom I recall you (or somebody else) had a way to open the Lucene search index with an external program. Maybe this would help to see what is contained in it?

**Comment by tesshucom** [comment]
> Maybe this would help to see what is contained in it?

It is helpful to know about the Debug tool.
The tool used to check the index is ``Luke``.
We will find some Luke clones on Github, but they are already frozen.
The reason is that from Lucene8.x, Luke is officially a Lucene subproject.
So the current official version Luke is included when you do a full Lucene download.
(One of the reasons to update Lucene. Old Lucene is difficult to debug.)
Just start the GUI and use is easy!

> Unless it deteriorates, it seems to work normally by itself.

Deterioration has been confirmed.
So while this is a valuable report, it seems a little difficult to confirm.

For example, an assumption can be made that a restart is not causing a state change.
We can assume that the first scan does not run properly and succeeds after several runs.
Observing what's going on may be meaningful, or may be waste time.

I think the first troubleshooting step is to repair the server boot architect.
Next, find out if this failure can be reproduced.

Investigation is difficult and lacks consistency if the existing implementation is not a version guaranteed by UT.

**Comment by di72nn** [comment]
>     * Move/rename files or folders.
>     * "Scan media folders now", wait for it to finish.
>     * Run "Clean-up database".

That solves it, thanks! I misunderstood the meaning of the operations so I was using them in an incorrect order.
