### ISSUE TITLE
Unable to upgrade MySQL Server to 8.0.18

### ISSUE THREAD

**Issue by tstreit** [airsonic/airsonic#1498]
[catalina.txt](https://github.com/airsonic/airsonic/files/4177693/catalina.txt)

## Problem description

*When attempting to connect a MySQL Server 8.0.18, war file deployment fails, catalina.txt file contains the output of tomcat console.*

### Steps to reproduce

*Upgrade mysql database to at least 8.0.18 or later.*

1. *Upgrade MySQL Server, in my case I compiled it from source.*
2. *Import  mysql-connector-java-8.0.18.jar in tomcat/lib directory*
3. *Restart tomcat.*

## System information

 * **Airsonic version**: *10.5.0-RELEASE – November 7, 2019*
 * **Operating system**: *Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-76-generic x86_64)*
 * **Java version**: *OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)*
 * **Proxy server**: *nginx*
 * **Client**: *Chrome 79.0.3945.130, DSub on Android*
 * **Language**: *English*

## Additional notes

*Would like to be able to upgrade database server without restriction.*

**Comment by randomnicode** [comment]
`tx_isolation` was renamed in MySQL 8.x, but the current airsonic version still comes packaged with an outdated driver (5.x).

Airsonic provides an ancient version of the mysql connector embedded in its war file here: https://github.com/airsonic/airsonic/blob/master/airsonic-main/pom.xml#L558-L563

The `runtime` scope means it's packaged with the jar.  Adding an additional jar to the container likely won't help, it seems in your case it was just ignored (it tried connecting with the 5.x driver).

Your options are:
- Plead with airsonic devs to update their dependencies. MySQL 8.x has been around for 2 years now and I'm surprised no one's complained yet. I guess either no one uses it on 8.x, or they tried, failed and moved to different options.
- Update the dependency yourself on your own fork
- Use a fork of airsonic with newer and more current dependencies, such as https://github.com/airsonic-advanced/airsonic-advanced

**Comment by tstreit** [comment]
Thanks for the reply.

For now I just pointed my airsonic instance to another older database that is still supported, so it's working but not ideal. I did try to update the dependency myself but unfortunately I am not as familiar with the code base to do it properly.

I understand that changing this in the code base would be a massive undertaking and then it would force all the other users of airsonic to have to upgrade their MySQL server which is also not ideal. I wonder if a simple if/else statement would be sufficient.

Some thing like
if(mysql-server = 5.7) {
  use-this-driver-5.7();
} else {
 use-this-driver-8.0.18()
}

Not sure if this is feasible or practical. Would be interested in what the devs have to say though.

**Comment by randomnicode** [comment]
Like I said, if you are unfamiliar with changing the dependency yourself, you can use an existing fork with already updated dependencies here: https://github.com/airsonic-advanced/airsonic-advanced

This is the latest war from the fork: https://github.com/airsonic-advanced/airsonic-advanced/releases/download/10.6.0-SNAPSHOT.20200208071712/airsonic.war that you should be able to deploy as any other airsonic wars (and should work with mysql 8.x). There also might be other forks around with updated dependencies.

The new mysql driver supports 5.x and 8.x dbs (https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-whats-new.html), so that `if` statement isn't necessary, and a driver upgrade wouldn't force anyone to upgrade their dbs. I suspect you just need the version change in the pom (one-line). I do not think it's a massive undertaking.

**Comment by tstreit** [comment]
Thank you! I just used that war file and it works perfectly.

**Comment by randomnicode** [comment]
👍

**Comment by jvoisin** [comment]
This should be fixed by 8651a405
