### ISSUE TITLE
Error installing airsonic server 

### ISSUE THREAD

**Issue by hasamba** [airsonic/airsonic#1658]
## Problem description

wanted to switch to mysql installation, 
upgraded mysql to latest version 5.6.46

### Steps to reproduce

1. run java -Xmx2G -jar airsonic.war

## System information

 * **Airsonic version**: *10.6.1*
 * **Operating system**: *ubuntu*

## Additional notes

here is the full log: https://privatebin.net/?717ddd2eb190dc75#HV4Mw6L8wm8yoyGLJhEbadmoL4MydevA9RbetHcP8S3y

**Comment by randomnicode** [comment]
This log seems like you put a bunch of different runs (with different log levels) into the same log file and uploaded the whole thing. That's hard to debug. Maybe try deleting the log and then restarting the server so the present _current_ issue you're facing can be isolated?

For instance, the first run seems like you had your jdbc url wrong: `mysql://10.0.0.190/airsonic?sessionVariables=sql_mode=ANSI_QUOTES&useSSL=false` is incorrect

Then in a subsequent run you were running into a timezone issue. Your server defines `Jerusalem Standard Time` which isn't a timezone. Either specify a correct time zone (like `Asia/Jerusalem`) for your server (in my.ini/cnf or wherever), or configure your mysql client connection string to connect with a timezone (`serverTimezone` is the property name)

Later on (skipping the whole middle), you have an issue with migration checksums because you likely changed some parameters and the old migrations in the database now don't align with what the new migrations expect (maybe the mysql maxvarcharlimit). You should delete your tables and start anew with the new params for this. [`airsonic-advanced`](https://github.com/airsonic-advanced/airsonic-advanced) is a little more flexible with changing params, but vanilla airsonic isn't.

I guess it's hard to debug what issue you'd actually like to diagnose and are asking assistance for.

Finally Mysql 5.6.* is NOT the latest MySQL. That'd be the 8.x series. Even in 5.x series, 5.7 is a more recent version.

**Comment by hasamba** [comment]
> 
> 
> This log seems like you put a bunch of different runs (with different log levels) into the same log file and uploaded the whole thing. That's hard to debug. Maybe try deleting the log and then restarting the server so the present _current_ issue you're facing can be isolated?
> 
> For instance, the first run seems like you had your jdbc url wrong: `mysql://10.0.0.190/airsonic?sessionVariables=sql_mode=ANSI_QUOTES&useSSL=false` is incorrect
> 
> Then in a subsequent run you were running into a timezone issue. Your server defines `Jerusalem Standard Time` which isn't a timezone. Either specify a correct time zone (like `Asia/Jerusalem`) for your server (in my.ini/cnf or wherever), or configure your mysql client connection string to connect with a timezone (`serverTimezone` is the property name)
> 
> Later on (skipping the whole middle), you have an issue with migration checksums because you likely changed some parameters and the old migrations in the database now don't align with what the new migrations expect (maybe the mysql maxvarcharlimit). You should delete your tables and start anew with the new params for this. [`airsonic-advanced`](https://github.com/airsonic-advanced/airsonic-advanced) is a little more flexible with changing params, but vanilla airsonic isn't.
> 
> I guess it's hard to debug what issue you'd actually like to diagnose and are asking assistance for.
> 
> Finally Mysql 5.6.* is NOT the latest MySQL. That'd be the 8.x series. Even in 5.x series, 5.7 is a more recent version.

thanks for your quick reply.
1. i had MySQL community server working for year, i read somewhere that the varchar problem can be fixed by latest version so i downloaded latest version of mysql and it upgraded for me to this version, unfortunately if ruined my kodi db but thats for other threads :)
2. indeed i had the GMT and varchar problems but i didnt had any log then, i just enabled it now, very strange...

anyway now i dropped all tables and deleted the log file...
here is the new one: https://privatebin.net/?04f5bc4a21c7fc02#6cEjYdStqcjo65fVYCNQ4RYkgYdmDYcLmC9QTrTjGk7A

**Comment by randomnicode** [comment]
>  i had MySQL community server working for year, i read somewhere that the varchar problem can be fixed by latest version so i downloaded latest version of mysql and it upgraded for me to this version

Again, not sure the method by which you're upgrading, but this is an _old_ MySQL version and will likely not solve any varchar issues. You need to upgrade to a more recent version to see any benefits (like 8.0)

> anyway now i dropped all tables and deleted the log file...
here is the new one: https://privatebin.net/?04f5bc4a21c7fc02#6cEjYdStqcjo65fVYCNQ4RYkgYdmDYcLmC9QTrTjGk7A

Can't see it. It's encrypted.

**Comment by hasamba** [comment]
> 
> 
> > i had MySQL community server working for year, i read somewhere that the varchar problem can be fixed by latest version so i downloaded latest version of mysql and it upgraded for me to this version
> 
> Again, not sure the method by which you're upgrading, but this is an _old_ MySQL version and will likely not solve any varchar issues. You need to upgrade to a more recent version to see any benefits (like 8.0)
> 
> > anyway now i dropped all tables and deleted the log file...
> > here is the new one: https://privatebin.net/?04f5bc4a21c7fc02#6cEjYdStqcjo65fVYCNQ4RYkgYdmDYcLmC9QTrTjGk7A
> 
> ~Can't see it. It's encrypted.~
> 
> Your issue was already pointed out to the devs here in #1563 and they were warned of related issues.
> You haven't specified your character set, but summarily, your issue is:
> (a) a very old MySQL version that has a very narrow allowed column width. MySQL 5.6 has an allowed column width of 767 bytes, and 5.7 onwards it is 3072 bytes.
> (b) A default varcharlimit in airsonic of 512
> (c) Even if you're using a characterset that uses 1 byte per varchar (which I doubt you are), you'll run into issues with a 2 column index or table (512 x 2 = 1024 > 767). More likely you're using utf8 (3 bytes per char)
> 
> So you can:
> 
>     * Upgrade your Mysql to something more modern so your max limit goes up
> 
>     * Reduce your maxvarcharlimit param in airsonic.properties to something lower before running migrations
>       
>       * How much lower depends on your db's charset. Assuming utf8 (3 bytes/char), and assuming the max number of varchar columns in any airsonic index is 2, you should lower it to like 767/(3x2), so like 126 or something. Lower if you use utf8mb4 (4 bytes/char) or if there are indices with more columns.
> 
> 
> Also please turn down your log level. Makes it difficult to debug

- you are right, i found that there is mysql 8 but the installer is only 32bit and mine is 64bit, there is a binary version of 64bit, should i download it and just overwrite files?
- i changed the VARCHAR to 126 as you suggested, changed the log to WARN, deleted the tables and rerun the server.
here is the log: https://privatebin.net/?55e201cc4dc427e8#FeoLPhYZArQ6d9GXU3w78GJojG5wgibzRRqoEpSVFyQg

**Comment by randomnicode** [comment]
> you are right, i found that there is mysql 8 but the installer is only 32bit and mine is 64bit, there is a binary version of 64bit, should i download it and just overwrite files?

Perhaps questions about upgrading mysql would be better asked in a mysql forum?

> i changed the VARCHAR to 126 as you suggested, changed the log to WARN, deleted the tables and rerun the server.

Yeah, I guess it doesn't work. 126 is too small a limit to fit some migration data in.

I guess your only recourse is to update Mysql (or use MariaDB or postgres)

**Comment by hasamba** [comment]
> 
> 
> > you are right, i found that there is mysql 8 but the installer is only 32bit and mine is 64bit, there is a binary version of 64bit, should i download it and just overwrite files?
> 
> Perhaps questions about upgrading mysql would be better asked in a mysql forum?
> 
> > i changed the VARCHAR to 126 as you suggested, changed the log to WARN, deleted the tables and rerun the server.
> 
> Yeah, I guess it doesn't work. 126 is too small a limit to fit some migration data in.
> 
> I guess your only recourse is to update Mysql (or use MariaDB or postgres)

ok,
i uninstalled mysql5.6 and installed latetst mysql 8
create new db, deleted airsonic/db folder (dont want to upgrade).
now same problem with VARCHAR 3072
here is the log: https://pastebin.com/qwryknLL

**Comment by randomnicode** [comment]
Again this exact scenario is described and predicted in #1563

I assume you never specified a charset, and thus you are running the default charset.

Default airsonic migrations _will_ fail on newer versions of mysql/mariadb. That's because the default charset is now `utf8_mb4` (4 bytes/char) instead of `utf8` (3 bytes/char). The maintainers here were told about this issue in #1563 along with the solutions.

So lets do the math here at the point the exception (any of them!) happened:
- you have a 2 column index: (artist, album)
- each column is 512 chars (default for airsonic)
- so the total index now is 1024 chars wide
- if you have charset that uses 4 byte per char, that makes it 4096 bytes total
- your limit is 3072

Switch to [airsonic-advanced](https://github.com/airsonic-advanced/airsonic-advanced/releases) OR lower your maxvarcharlimit param to something lower until the math checks out (but not low enough to make the migrations fail).

Hope this helps?

**Comment by hasamba** [comment]
>  maintai

seems to work with VARCHAR=383
thanks alot for your help

ps. i will try airsonic advanced, didnt know about it...and mysql8 sucks, all my apps kodi/nextcloud works alot slower than on mysql56....now i need to bug people on mysql forums :)
