### ISSUE TITLE
DISCUSSION : the importance of UI

### ISSUE THREAD

**Issue by biconou** [airsonic/airsonic#479]
To make airsonic a real brand new soft, I think we should consider to gather efforts on a modern UI (despite the fact I'm not a front oriented developer).

Did you see that ? (https://github.com/phanan/koel) 
It seems to really rock.

Another thought I have is, to avoid having to work on too much things, it would be cool to have a nice responsive player UI that could be easily ported to mobile devices. Having to develop and maintain a native mobile is a pain. 
This should be taken in consideration for choosing a front framework.

**Comment by muff1nman** [comment]
Yes I think we should start planning to do this. The example you've shown is quite slick. One thing I think we could do is package a completely rewritten ui alongside our current one with a different context path (i.e. http://localhost:8080/airsonic/modernui) to keep things agile.

**Comment by biconou** [comment]
Exactly.

**Comment by akpdw** [comment]
I have found that one of the nice things about working with the *sonic backend is that it's pretty straightforward Java code.  It uses Spring, which is a little bit clunky but works and has held up well over time, builds with Maven (I prefer Gradle but whatevs), etc. Pretty standard. There are a lot of Java programmers, and so there are a lot of people who are out there who could contribute code.

The frontend...  Well, the frontend still uses layout tables and frames.  (FRAMES!)  So it needs a lot of work.  But the UI needs are pretty simple--the hope would be that 90% of the time people would just be in the music player, and otherwise you're just doing library management and maybe updating some settings.  So get rid of the out-of-date HTML (DID I MENTION IT STILL USES FRAMES?!?), get a nice modern responsive framework (Bootstrap, Foundation, or something else that's similarly robust and popular), patch it together with some jQuery, and you're probably set.

Plus, like there are a lot of Java programmers, there are a whole lot of people who can do HTML5, CSS, jQuery, and a responsive framework like Bootstrap.  If we don't need any more than that, there's no reason to bring in anything else.

**Comment by plastikman** [comment]
For me personally I use *sonic in a web browser in a background tab.  ON my phone I use an app like Dsub to stream, having a "Slick UI" is not really a requirement.

**Comment by biconou** [comment]
What do we call a "Slick UI" ?

**Comment by biconou** [comment]
@akpdw Do you mean that using a "heavy" js framework (Angular, React) would would be overkill ?

**Comment by jooola** [comment]
I don't know how it actually works, but if we could reach the point of : 
frontend/backend I think this could e a great step forward.
For example we have a fully functional backend ( search, scan, set user passwd, ...) and on the top of that we build a great simple UI ( that looks like to actual one ) that simply call the function.

with this structure we could easily build a UI using lightweight framework ( not bootstrap or the one mentionned above) but a mix of fontawesome, skeleton, normalize, and scss. Or [Purecss](https://purecss.io/) with font awesome.

**Comment by akpdw** [comment]
@biconou Yes, overkill.  :)  Plus they carry steep learning curves, and kind of want your application to be built to use them. If you really need the functionality that might be worthwhile, but if you don't...

@joola I feel like half the pages we have are administrative pages. I don't know that there is any huge win in moving those over to a full backend RESTful server architecture. But for the player (and playlist/library management?), sure.

Also fontawesome and skeleton or purecss or whatever is fine.  I'd just want to avoid anything new or small enough that it might be unmaintained in a year or two.

Really whoever ends up owning the UI redesign should have a lot of leeway in what tools/libraries/etc. we use.  Is there a volunteer for that job yet?

**Comment by biconou** [comment]
I think we should start to work on a new UI only for the navigation + player fonctionnalities. 
Administrative screens can stay as is. 
Personally, I would be glad to work on some client librairies coded in a JS (like) technology that act as a client in front of a brand new rest API as proposed by @muff1nman.
But, as I miss UI design skills I'd like to work in collaboration with someone good at creating a responsive layout. Who can ? 
I've thought of deezer as a good design guide line, no ?

**Comment by jooola** [comment]
I would like to be part of the UI work !

I think we should keep the current structure as guide line ! Some parts need a total redesign like the right.view or the settings !

**Comment by biconou** [comment]
@jooola How should we start ? I think that, as a designer you will have an important role at the begining.
Proposition : Can you start un first draft layout on witch I could begin to add some js code ?

**Comment by jooola** [comment]
@biconou First I think is to finish the html5 player. ( Sorry but let's finish this first before starting new huge changes)
After this we need to move every html4.1 code to html5. So this will also be a huge clean up !

After those few steps we can start on thinking on the design !
But again I think that the current UI is pretty good and it only needs few tweaks !

I will start working on this next week maybe. But it's summer and I don't want to pass the sun !

**Comment by joshuaboniface** [comment]
As an odd power user, I'll share my perspective.

I'd love a newer interface - frames are gross, and the interface can be quite cumbersome and slow at times. It's really showing its age.

Specifically re: the Administrative interface, I agree that not much change is needed, but for a different reason - I'm one of those people who manages `airsonic.properties` manually via config management/`vim`, so I don't use the Administrative interfaces at all really. If it could be made hidden/disabled via an option for those of us who hate having `airsonic.properties` rewritten, or otherwise kept separate from the main UI, that would be a fantastic feature.

**Comment by akpdw** [comment]
Huh.  I wonder if you could use a good layout framework plus some super-hacky javascript to get rid of the frames system that we currently have.  That would allow us to update some of the most-used sections/pages (or first-used pages for new users) and leave the rest to be done piecemeal.

I don't really know if that is possible, though.  I may give it a try, though, just to see.

**Comment by bfkelsey** [comment]
A move to using Kotlin for the backend would be great. It might attract more people to contribute as well.

**Comment by jooola** [comment]
Closing this since we now have a experimental UI working !

See https://github.com/airsonic/airsonic-ui/
