### ISSUE TITLE
Import Subsonic-svn history 

### ISSUE THREAD

**Issue by jooola** [airsonic/airsonic#482]
I suggest we import the subsonic-svn history from the libresonic repo.

What do you think @muff1nman ?

https://github.com/Libresonic/subsonic-svn

**Comment by muff1nman** [comment]
You mean as a separate repo, right? I initially toyed with the idea of actually importing it into the git history of airsonic, but then figured that would be a bad idea because it would change the sha sums of all the git commits.

I think as a separate repo would be a great idea and will plan on doing that.

**Comment by jooola** [comment]
No i meant as separate repo for the history.
Something like airsonic/subsonic-svn ( just like libresonic/subsonic-svn )

I don't know what will happen to libresonic/subsonic-svn but I think we better keep it with us and if we need to link too any old commit we link using our own repo

**Comment by muff1nman** [comment]
Done.
