### ISSUE TITLE
Communication Channels

### ISSUE THREAD

**Issue by muff1nman** [airsonic/airsonic#487]
What would folks like to use for communication channels. When at libresonic we used a combination of github, irc and reddit. Currently for airsonic, we have github (obviously), but we probably need other less formal places for discussion/questions. I registered the freenode `#airsonic` channel, but I know @biconou was interested in trying slack. Is mattermost another good option?

**Comment by jooola** [comment]
The IRC/Reddit communication channels where fine to me !
We can create a Slack instance but I try not to use closed source softwares. So I won't be part of this channel. We could set up a mattermost instance but again we need to provide the service and host it somewhere (and that's more work).

We should stay as far as possible from self-hosted services.

**Comment by biconou** [comment]
But github is not self-hosted.
I don't use slack yet but I personally do not like IRC/Reddit.
Setting up a mattermost needs to find a place to host it. Isn't it cumbersome ? 
what about sandstorm ? https://oasis.sandstorm.io/

**Comment by CharlesSchaack** [comment]
Why not just a discord channel? Easy to setup, widely in use and intuitive. It's closed source and not selfhosted but I really don't see why that's a negative for this use case. I think it'd be one of the easier solutions that allow people to just hop in with a quick question. It's also nice to have past conversations retained so that people do not have to run a bouncer like ZNC to see chat history.

**Comment by jooola** [comment]
I think slack or mattermost will be used for devs. Any help will be asked on IRC or Reddit.
Since i'm not one of the devs I won't ask too much here.

But I think we should use services that already exist, free, and not closed sources.

If we really think we are going to use mattermost, I can host it but just like any services it takes times to handle it ( upgrade, management, ... ).

@muff1nman Had a great idea too simply set up a bridge between our communication services.

Personnaly I use Telegram, so we could set a bridge between IRC and Telegram. ( Just an example )

**Comment by Tapchicoma** [comment]
In the end of this discussion may you, please, add how to join this chats/discussions in the project README?

**Comment by jooola** [comment]
I will, just like the contibute page of the website it will be written somewhere !
https://airsonic.github.io/contribute/

**Comment by muff1nman** [comment]
What about matrix/riot? It might provide the right balance between low cost (IRC), open source (i.e. not Slack) and ease of use (it provides history at least).

I've setup the bridge between matrix.org and the `#airsonic` channel so we can try it out. From what I've seen its bi-directional.

**Comment by hschroedl** [comment]
My two cents as a non-contributor:

Might be a silly idea, but it appears that [Gitter](https://gitter.im/) was[ recently open sourced](https://news.ycombinator.com/item?id=14694283) under the MIT license. Looks like it also fits the bill, but maybe there's something I'm overlooking. Haven't really used it after all. 

Like I said, just an idea.

**Comment by jooola** [comment]
I already used Riot some time ago and I just remember that it is a great software ! ( specially matrix ! )

I think that we have our communication channels up !?
IRC/REDDIT/MATRIX !

Currenlty reddit isn't existing ( I can't create any subreddit )
but IRC and MATRIX is already up

**Comment by nvllsvm** [comment]
+1 to using Matrix or IRC. Using Slack would be negatively ironic for a project/community geared around openness. I personally would not use Slack even if it were the official.

**Comment by muff1nman** [comment]
Created the subreddit: https://www.reddit.com/r/airsonic/ and matrix is all setup I believe, so I think we can call this good.

**Comment by muff1nman** [comment]
Actually, need to update the readme still.

**Comment by muff1nman** [comment]
README updated. Now we should be able to call this done.
