### ISSUE TITLE
Please implement "https" urls for providers

### ISSUE THREAD

**Issue by gerroon** [airsonic/airsonic#585]
Hi

Currnetly it looks like the providers like last.fm run through http. What people listen should not be open to scoping, at least it should be as private as possible therefor I recommend implementing the https url (if they offer) for query prividers.

thanks

**Comment by jooola** [comment]
I tried to fix this by simply replace all last.fm urls with secured one but I think we need to upgrade last.fm scrobbler service.
While searching I found [hardcoded link](https://github.com/airsonic/airsonic/blob/master/airsonic-main/src/main/java/org/airsonic/player/service/AudioScrobblerService.java#L177).
This leads use to the deprecated last.fm API https://www.last.fm/api/submissions

Maybe lets try to upgrade totally the service so we can use latest last.fm api.
For scrobbling ; https://www.last.fm/api/scrobbling

https://www.last.fm/api/intro

**Comment by tari** [comment]
Seems like we could be using our last.fm library here instead of rolling our own scrobbler? [de.umass.lastfm.scrobble.Scrobbler](https://github.com/jkovacs/lastfm-java/blob/master/src/main/java/de/umass/lastfm/scrobble/Scrobbler.java#L67)
It doesn't support the new (HTTPS) API either, but it makes more sense to contribute that improvement upstream and switch to using it.

Everything else is already HTTPS with a sufficiently new library, but we need a new release upstream to get it. https://github.com/jkovacs/lastfm-java/pull/9

> And why not get our own api key instand of using subsonic's one ?

I opened a new issue for that, since it's independent of this: #592.

**Comment by jvoisin** [comment]
This was done as much as possible in #952
