### ISSUE TITLE
Version 10.1.0 does not respect logging.file location for displaying logfile in UI

### ISSUE THREAD

**Issue by mshick** [airsonic/airsonic#630]
## Problem description

Setting a `-Dlogging.file` location on command line for the standalone war will not update the loaded path for the UI About section.

### Steps to reproduce

1. Set a custom logging location, outside of your working forlder e.g., `/usr/local/var/log/airsonic.log`
2. Start Airsonic
3. Visit the About section. If the default airsonic.log path does not exist you'll get errors. If it does exist, but is not the log location, you'll see nothing (it's reading the wrong file)

## System information

 * **10.1.0-RELEASE**
 * **macOS**

## Additional notes

Noticed this when updating the Homebrew formula to latest.

**Comment by muff1nman** [comment]
So just to confirm, this is something that was working in  `10.0.1`?

**Comment by mshick** [comment]
@muff1nman I know for certain is was working on 10.0.0. A little less certain about 10.0.1. Is it important for me to test, or does that give enough info?

**Comment by muff1nman** [comment]
Looking into this a bit, the behavior where logging.file would have worked would be before 07ff71df0cafac35878b6f9547df66711152e6c9. After that change the setting should be ignored/overwritten. So I would expect that the last time this would have worked would have been before any of these:

```
$ git tag --contains 07ff71df0cafac35878b6f9547df66711152e6c9
v10.0.0
v10.0.1
v10.1.0
v6.2
v6.2.1
v6.2.beta2
v6.2.beta3
v6.2.beta4
```
But I think I trust you more than I trust my back of the hand git searching skills. So lets put that aside for a second. What should be the behavior? Are you relying on setting `logging.file` for homebrew? Why not leave it in the default location (`airsonic.home/airsonic.log`)?

The current coded behavior is to always override the `logging.file` property. I suppose we could change it so that it would obey what the user set, but would probably require some code changes. We would probably have to change HelpController to directly inject the `logging.file` property and remove the static `getLogFile` method in SettingsService altogether.
