### ISSUE TITLE
Allow to delete default admin user

### ISSUE THREAD

**Issue by Tapchicoma** [airsonic/airsonic#640]
## Problem description

Currently, after installation, Airsonic creates default user `admin` that is used to make first configuration.
The problem is that there is no way to delete/disable such user - it rises security problem as any "bad" person already knows existing login.

Possible solutions:
- Allow to delete such user if any other user with admin rights present
- Allow to rename user on installation
- Allow to disable this user

**Comment by jooola** [comment]
Agreed ! :+1:

**Comment by spikespaz** [comment]
2017!? This is an important feature I think. I'd like to see an update on this if possible.

**Comment by jvoisin** [comment]
I don't think that anybody is actively working on this, feel free to send a PR, I'll be happy to review it.

**Comment by ohnonot** [comment]
I have to chime in.
Ability to delete, or rename.
Having the login admin openly on the wild web, even on a non-standard port, is an invitation for hackers.

Sorry for not being able to make the required changes to the java code myself.

Otherwise a big thank you, this is working nicely, I was even able to watch video on my phone.
