### ISSUE TITLE
Feature Request: Mobile Version

### ISSUE THREAD

**Issue by mccorkled** [airsonic/airsonic#680]
Any chance to get an phone/table responsive version? I have finally been ripping my music collection and pulled AirSonic up on my phone and I couldn't see anything without zooming in and out a bunch. If this is not likely, could you recommend a music software similar to this that would work on tablets?

Thank you

**Comment by jooola** [comment]
Hi @mccorkled ,
we won't rework the current UI to get it responsive to fit on mobile devices. Since the current UI is really old and this would be too much work for the small number of contributors that commits in airsonic.
So the best solution I can propose to you is to use a mobile app ( android / iOS ) that connects to airsonic/subsonic. 
[Here is a list of some apps](https://airsonic.github.io/docs/apps/)

Another thing is that we want to rebuild from scratch a [new UI,](https://github.com/airsonic/airsonic-ui) since we use angular/boostrap to build it we could someday port it to fit small screens, but for now we are trying to get it done.

**Comment by dorel14** [comment]
I also recommend DSUB both for phone and tablet

**Comment by acroyear** [comment]
My own web/html5 apps (SubFire and SubFire Mobile specifically) seem to handle airsonic just fine. I just tried the main app out on the demo server. Feel free to try them out (they're always free).  https://subfiresuite.com/

The mobile version is specifically optimized as a PWA for phone screens, and I use it daily.

**Comment by acroyear** [comment]
You didn't name that requirement in your description above. You asked for a more mobile-friendly page. :)

Only a fully native app (whether for subsonic/airsonic or any other media server) is going to be able to handle downloads and off-line listening.  Updating the airsubsonic UI to their new UI will not change that, because it is still an html5 solution dependent on the API and streaming the files rather than downloading them into a local storage. HTML5 has limits on the size of local storage where-as an app has more freedom to download.

As noted, Dsub is capable of caching the files, but it works by caching the play queue (with a by default limited number of songs it will fetch ahead as well as a limit on the size of the cache).  It isn't a case of "download this album to play later".   I don't know if Dsub persists the last playlist info when going offline; the Subsonic android app does not.

**Comment by mccorkled** [comment]
I mean no internet. We will still have access to our NAS via wifi.

**Comment by acroyear** [comment]
AH. Well, it is possible for me to package up either SubFire (mobile or classic) to be dropped onto any local webserver on your own network behind the lines.  I can only provide limited support, and since it isn't my primary means of distribution, there's no automatic upgrade path the way there would be if running off the cloud or through an app store.

**Comment by mccorkled** [comment]
I see
