### ISSUE TITLE
Use embedded art in the song if it exists

### ISSUE THREAD

**Issue by QuillOmega0** [airsonic/airsonic#694]
Would it be feasible for Airsonic to use embedded art in the song if it exists, over the album art in the folder?

**Comment by gerroon** [comment]
See this if you want to get confused more about this :) 
https://github.com/airsonic/airsonic/issues/667

**Comment by QuillOmega0** [comment]
Let me elaborate. It should be setup so that airsonic will look at the audio file's ID3v2 tag: http://id3.org/id3v2.3.0#Attached_picture
And if it sees that set, prioritize that over any album cover art.

**Comment by enaloha** [comment]
@QuillOmega: why would you add a cover image for the album to the folder if you didn't want that image shown? If you prefer another image, just make it the cover.jpg Or simply delete the cover.jpg and airsonic will use the embedded image of the first song.

@gerroon: I don't understand why you are still confused about this. I explained exactly how the the cover priorities work in #667 Just read it and adjust to it.

**Comment by gerroon** [comment]
@enaloha I would like a dev to also give us an input. I am not sure, I just have inconsistent results.

**Comment by QuillOmega0** [comment]
@enaloha This would be a case of precedence. Some songs may have a specific art for it that should override cover art. Special edition albums for example or songs by certain artists. By having Airsonic set it so that if a song that is playing has the id3v2 tag for Attached Picture set, it takes precedence over an cover.jpg

**Comment by enaloha** [comment]
@gerroon actually, jooola has commented with a thumbs up in the #667 thread and again referenced that thread. So if you have a reproducible bug, please post the steps needed to reproduce the behavior.

@QuillOmega0 I understand your original request. I personally am not aware of a commercial album that has different artworks for different songs. Can you provide an example? If you are talking about VA compilations with songs that were assembled from individual songs, then the VA album still only has one cover. If you want to see the cover of VA compilations that you created, simply make a playlist.

**Comment by jooola** [comment]
Hi, this sounds like a duplicate post to #667.
@QuillOmega0 Hope you found your answer ?

**Comment by etyrnal** [comment]
Is any of this related to the problem where, when using android *sonic clients, anytime a song has no embedded artwork, it seems to serve up some arbitrary artwork (first artwork it can find in an album/artist?)?

I have large collections of miscellaneous semi-unorganized mp3's, and they always seem to show a hand full of wrong artwork.  I'm assuming that arisonic is assuming that, if an mp3 doesn't have an embedded artwork, it should check the containing album for one and use that, and if the album doesn't have it, then it should use the artists?

I have lots of music that's unorganized because it's from a lot of underground and unsigned artists etc, so these tracks don't have art, and since Arisonic can't seem to handle working directly with song lists i put them a generic folder like "aaaaa" (just a random example), and create a folder inside it called "misc songs" -- there can be 2700 songs in that folder.  And Airsonic seems to assume that the first artwork it can find in that folder should be applied to any/all other artless mp3's in that folder.  Its a wrong assumption.

**Comment by enaloha** [comment]
This is a problem with the client, not airsonic. In fact, airsonic handles VA compilations just great. I have lots of compilations with various artists and various albums. Selecting the album in airsonic's web client shows the artwork of the individual songs just fine. Try it yourself with the native airsonic web interface and you will see that it works just as you wish. Your request needs to directed at whoever handles the client you are using.

**Comment by etyrnal** [comment]
I was going to say... it would do it on any client I used I've tried multiple Android clients

**Comment by jooola** [comment]
> Would it be feasible for Airsonic to use embedded art in the song if it exists, over the album art in the folder?

Where ? in the UI / in the API ?
For what ?
Which use case ?

> This would be a case of precedence. Some songs may have a specific art for it that should override cover art. Special edition albums for example or songs by certain artists. By having Airsonic set it so that if a song that is playing has the id3v2 tag for Attached Picture set, it takes precedence over an cover.jpg

@QuillOmega0 Are you talking about the album cover in the airsonic web UI ? about VA compilations ? since it is an album I don't see the point of using a specific song cover for the album and this joins the #667 issue. If you are talking about the Dsub mobile player with the playing cover, I think yes this could be an option but I don't think those are small changes.
