### ISSUE TITLE
Double set of java arguments passed

### ISSUE THREAD

**Issue by ishmaelen** [airsonic/airsonic#714]
## Problem description

JAVA_OPTS are passed by config and arguments

### Steps to reproduce

1) docker pull..

2) docker run -v data:/var/media/data -v music:/var/media/artists -v playlists:/var/media/playlists -v podcasts:/var/media/podcasts -e JAVA_OPTS="-Dserver.host=127.0.0.1 -Dserver.port=4041 -Dserver.contextPath=/airsonic" -p 4041:4041 -d airsonic/airsonic

3) ps -ef | grep java

java -Xmx256m -Dserver.host=0.0.0.0 -Dserver.port=4040 -Dserver.contextPath=/ -Dairsonic.home=/airsonic/data -Dairsonic.defaultMusicFolder=/airsonic/music -Dairsonic.defaultPodcastFolder=/airsonic/podcasts -Dairsonic.defaultPlaylistFolder=/airsonic/playlists -Djava.awt.headless=true -Dserver.host=127.0.0.1 -Dserver.port=4041 -Dserver.contextPath=/airsonic -jar airsonic.war

## System information

 * Airsonic version: 10.1.1-RELEASE – December 16, 2017

 * Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.51-3 (2017-12-13)

 * Java version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-1~bpo8+1-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by tari** [comment]
This looks like intended behavior- options specified via `JAVA_OPTS` are added to the command line, and the defaults for those options that are set automatically should need to be changed. You can set the port with `-e AIRSONIC_PORT=4041`, and `server.host` shouldn't need to be overridden because Docker is running in an isolated network namespace so in either case it's not accessible from outside the host machine without further configuration (like `-p`).
