### ISSUE TITLE
New installation - getting 404 error

### ISSUE THREAD

**Issue by mmcc-xx** [airsonic/airsonic#719]
Hi - I am attempting to install Airsonic v10.1.1-RELEASE on Ubuntu Artful. Java version is 1.8.0_161 - I'm on the Oracle version.

I've installed for a standalone WAR per the documentation with the systemd steps. Service is starting, and seems to be running. There are no errors in the log file - just entries indicating that the service is starting up and running normally. But when I try to hit the server, I get a 404 error. Hitting the server causes no entries to be written in the log file.

I'm running subsonic on the same box and it is serving up pages just fine. Both server processes are running as their own user.  I tried stopping subsonic and having airsonic listen on port 4040, but I still got a 404 error.

Any suggestions for what to try or what log files to look at?

**Comment by mmcc-xx** [comment]
Well, I worked around it by using the tomcat installation. I still don't know why standalone didn't work though.

**Comment by di-dc** [comment]
What was your CONTEXT_PATH set to? Were you hitting the correct URL including the context path, eg: http://localhost:4040/airsonic ?

**Comment by mmcc-xx** [comment]
The installation doc (https://airsonic.github.io/docs/install/war-standalone/) didn't say anything about setting a context path, and I was just hitting straight up http://localhost:8080/
Per the doc "Airsonic should be running at http://localhost:8080 if installed locally"

I'll try it with /airsonic

**Comment by di-dc** [comment]
(I should caveat first that I haven't done this, just doing some educated guessing.)

Looking at the systemd instructions, in the "Setup systemd service" section, there's this wget call:
wget https://raw.githubusercontent.com/airsonic/airsonic/master/contrib/airsonic.service

Pulling up that file, I noticed it's got the following lines:
Environment="CONTEXT_PATH=/airsonic"
Environment="PORT=8080"

So, if I'm reading all that right, it looks like following the systemd instructions puts you back on localhost:8080/airsonic, instead of just localhost:8080.

**Comment by mmcc-xx** [comment]
Well shoot. That certainly sounds like the problem. Perhaps the doc could be updated to note the proper URL when the systemd approach is used. Thanks!

**Comment by di-dc** [comment]
@jooola I think this one can be closed

**Comment by jooola** [comment]
@di-dc @mmcc-xx The owner of the ticket also can close it. :wink:
