### ISSUE TITLE
Total hour count seems to be an unsigned int?

### ISSUE THREAD

**Issue by seitzbg** [airsonic/airsonic#720]
## Problem description

Total hour count seems to be an unsigned int?
https://img.bsd-unix.net/screenshots/user1/194GO90e0.png

### Steps to reproduce

Add tons of music, view status bar @ bottom.

## System information

 * **Airsonic version**: 10.1.1-RELEASE – December 16, 2017
 * **Operating system**: Fedora 27 Server
 * **Proxy server**:  Nginx 1.12.1
 * **Client**: Firefox 58

**Comment by ae-g-i-s** [comment]
Is it possible that some of your media files contain invalid metadata?

From `src/main/java/org/airsonic/player/domain/MediaLibraryStatistics.java`:
```
private long totalDurationInSeconds;
```

Java's `long` is a signed 64 bit number, i.e. the largest positive integer is 2^63-1.
According to the screenshot, you have 214,706 files, which is a bit less than 2^18 = 262,144.
This means that on average, your tracks would have to be around 2^45 seconds in length to create a value of -1. This is approximately 1,115,689 years per track.

Assuming that something is coercing the format to 32 bits, i.e. 2^32-1, each of your tracks would still have to be approximately 165 minutes long to overflow the positive integers. While this is more realistic, it would only result in a value of -1 second, not 13,499,500 hours (that value is actually impossible to represent in signed 32 bit, assuming seconds).

Are you using the default DB backend or a more performant one? It would be interesting to find out which track is causing this to happen.

**Comment by seitzbg** [comment]
This issue has gone away so it must have been some wacky media.  Will I benefit from using mysql over the built in db?

**Comment by ae-g-i-s** [comment]
With the size of your library, probably. Not in situations with low load, but if you have more than one player at a time and need to search/filter a lot, a "real" DBMS will be beneficial. I mainly asked above because finding songs with insane durations is rather easy if you can just run a SQL query from a commandline client.

If you do notice slowdowns, you could try it out, though I'm not sure if there's a nice way to migrate your current DB/users/media folders to a different backend...

**Comment by seitzbg** [comment]
Thank your for the detailed reply!  Closing ticket since the problem is gone.
