### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by gerroon** [airsonic/airsonic#735]
Hi

Is there any eta for a newe release? It looks like the latest release was 5 months old.

thanks

**Comment by jooola** [comment]
Hi @gerroon, you know this project, any new release will come when it is ready.

Still we haven't merged much features since then, some PR are still waiting and could be merge before any new release. So this depends on @muff1nman. Either we release a quick bug fix version or we ship some small new features in.

Please ask in the to community channels next time. :beers:
