### ISSUE TITLE
Settings menu not working behind https reserve proxy server

### ISSUE THREAD

**Issue by lilarcor** [airsonic/airsonic#739]
I run it in docker version and it’s behind a https reverse proxy server. Everything works well except the settings button. It shows nothing when I click the settings. If I play a song, and click the playsetting at the bottom of my browser , the settings view shows. Playsetting is a subview of setting. So I trust it’s a bug in setting’s page code. Other sub views in settings also work as expected.

**Comment by sebastienbeau** [comment]
I had exactly the same issue (menu was not working due to an issue of mixed http / https content)

Maybe you have a bad configuration of your proxy

After reading some existing ticket like this one
https://github.com/airsonic/airsonic/pull/628
https://github.com/airsonic/airsonic/issues/243
And a lot of other ticket..

I finally see that documentation : 
https://github.com/airsonic/documentation/tree/master/proxy
And fix my configuration (I used Nginx)

**Comment by lilarcor** [comment]
thanks for your info. I read those docs and tried the conf (I am using apache), still no luck.

**Comment by lilarcor** [comment]
it's working after I added  "ProxyPreserveHost off"
ref https://stackoverflow.com/questions/24351782/proxypassreverse-dropping-https#27155124

 <Location /airsonic>
    ProxyPreserveHost off
    RequestHeader set X-Forwarded-Proto "https"
    ProxyPass  http://192.168.6.121:4040/airsonic
    ProxyPassReverse http://192.168.6.121:4040/airsonic
 </Location>
