### ISSUE TITLE
Airsonic doesn't render Asian characters

### ISSUE THREAD

**Issue by szakes1** [airsonic/airsonic#745]
Hi! 

I migrated from Ampache to Airsonic and I find Airsonic to be more intuitive, but I have been struggling with a "major" problem for me. Half of my library is Japanese and I find it to be extremely hard to listen to on Airsonic. When I scan for songs on my hard drive, it scans for them, but songs with Japanese characters are not rendered properly. Instead of Japanese characters I get strange question marks in square borders. There seems to be a problem with locales, but I am sure I have everything set up correctly. I even changed the UI language to Japanese just to see whether it would work. I also checked it on Android application - "Dsub". Songs with Japanese characters just disappear in the application, just like they do not exist. 

I checked GitHub for issues before, and I found the same issues like mine: [171](https://github.com/airsonic/airsonic/issues/171), [520](https://github.com/airsonic/airsonic/issues/520), [287](https://github.com/airsonic/airsonic/issues/287)

I tried what others suggested, but it did not work. For example, I created a tomcat upscript, which was suggested by a guy there, but upscript seems to be deprecated on Debian 9.4 Stretch. 

I really do not know what to do, I cannot listen to half of my library because of that. Can anyone help with that? I would be extremely glad if someone did!

![screenshot_20180521-132409](https://user-images.githubusercontent.com/20373275/40327012-a362e536-5d41-11e8-9e4d-28a695100d84.png)

**Comment by XTREEMMAK** [comment]
I am also running into this same problem. Renders Asian characters the exact same was as image above and does not play the file. I saw a post somewhere to edit the Tomcat8 server.xml file to include "URIEncoding="UTF-8" but that did not seem to help.

I'm running airsonic in a FreeNas 11 jail atm.

**Comment by tesshucom** [comment]
I handle Japanese files with two containers of Tomcat / Jetty.
There is no problem with Airsonic, it seems that it comes from the file encoding specific to JVM.
In case of Japanese, specify the following options when starting JVM (on Linux).

export LANG=ja_JP.UTF-8
JAVA_OPTIONS="-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Xms〇〇〇m -Xmx〇〇〇m"

Specification of URIEncoding is not necessary for recent Tomcat.

**Comment by szakes1** [comment]
@tesshucom Well, I am not experienced in tomcat, so I would gladly appreciate your help, if you told me, where I have to set these encodings. I am not sure, where I have to look, I just don't know wherre these file are.

**Comment by tesshucom** [comment]
For Tomcat, set it to setenv.sh and place it in bin.
For jetty, set it to / etc/default/jetty.
These are the recommended methods for each server.

In the case of standalone, there is a very polite commentary.

https://airsonic.github.io/docs/install/war-standalone/

At the bottom is a commentary on starting the daemon.
You can introduce environment setting file with wget.
The notes on Debian are also written.

**Comment by szakes1** [comment]
@tesshucom Thanks for your comment, but I still have some questions - just to be clear. 

In your previous comment you said you had these options set: 

"export LANG=ja_JP.UTF-8
export JAVA_OPTIONS="-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Xms〇〇〇m -Xmx〇〇〇m""

In the second line there is an option: "-Xms〇〇〇m", but the "〇〇〇" characters seem to be non-roman, so I am not able to type them in my terminal correctly, they just do not render. Is there any other way to properly write them or you made a mistake, while you were writing that comment? 

On the second thought; If I understood correctly, I have to save these options to "setenv.sh" file in /bin directory, am I right? There is nothing else I have to do after doing that? I do not have to run any program to have this script run on boot? Tomcat will automatically run this script after being run? 

Pardon my inexperience, but I have never worked with Tomcat before nor have I worked with Java.

**Comment by tesshucom** [comment]
1)
The first line is the locale setting handled by the OS.
This can be confirmed with the "locale" command in linux.

2)
The second line is the setting for Java.
Java has quite a lot of options.

https://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html

-Xms, -Xmx are not related to the current problem.
Sorry for being confusing.
(However, in the memory setting, it is commonly used when moving the server.)

In the case of Airsonic, when handling special characters, they need to be appropriate.
As a premise, these can be specified anywhere as long as it is before starting the server.
For example, even one line execution can be specified.

java -jar airsonic.war -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8

Wherever you are checking, you can write anywhere.

The recommended method suggested by the tool vendor indicates the position just before each server starts up.
(Because developers confuse themselves when writing in any position they like.)

#745 #171 #520 is also the same cause, there is a mismatch between the above OS ,JVM, and character codes handled by the program.
It is necessary to make appropriate settings and rebuild the DB data.
If correctly set, you can handle non-Japanese (Seleção etc.)

#287 adds a little more places to check.
I have not seen the detail, but · · ·.
· Hard code character string (character code of source code)
· Environment in which test music files were ripped
Generally, these are often the causes.

**Comment by Pollinopops** [comment]
I had the same problem using the standalone WAR. My locale on my Raspberry pi 3 running Debian are :

> LANG=fr_CH.UTF-8
LANGUAGE=
LC_CTYPE="fr_CH.UTF-8"
LC_NUMERIC="fr_CH.UTF-8"
LC_TIME="fr_CH.UTF-8"
LC_COLLATE="fr_CH.UTF-8"
LC_MONETARY="fr_CH.UTF-8"
LC_MESSAGES="fr_CH.UTF-8"
LC_PAPER="fr_CH.UTF-8"
LC_NAME="fr_CH.UTF-8"
LC_ADDRESS="fr_CH.UTF-8"
LC_TELEPHONE="fr_CH.UTF-8"
LC_MEASUREMENT="fr_CH.UTF-8"
LC_IDENTIFICATION="fr_CH.UTF-8"
LC_ALL=

Looking into "About" and the new ">more" section in the web interface I noticed a warning under "Locale" telling me that I am using US-ASCII and that I might encounter some problem with character encoding.

The solution for me was to add

`-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8`

in my airsonic.service file. 
I have no idea why my java doesn't use the system default locale...
Hope it helps others having the same issue.
