### ISSUE TITLE
How can I disable last.fm genre integration?

### ISSUE THREAD

**Issue by kaysond** [airsonic/airsonic#763]
Is there a way to turn off the last.fm integration? I couldn't find anything in the settings.

I keep ending up with weird or incorrect, descriptions or the annoying "Keep stats clean" image because the tags I use aren't the ones from last.fm -
https://imgur.com/v9wNuRL
https://imgur.com/a/4q8lzMa

I also don't particularly want to send all of my info to them. Thanks!

**Comment by heyarne** [comment]
Under Settings → Personal, there is a tick box that reads "Register what I'm playing at Last.fm". Is this the setting you're looking for?

**Comment by jooola** [comment]
Nope, you can't disable it using a built-in option... Agreed it's a bit strange. But what you can do is to block any access to last.fm api, using the system hosts file.

See this comment to get the hosts to block : https://github.com/airsonic/airsonic/issues/712#issuecomment-370432076

**Comment by heyarne** [comment]
Ah, now I understand. From what I can tell, it can't be disabled because the ID3 Tags are standardised. Airsonic and many other tools will assume they can interpret the key-value-pairs according to the standard. If you want to organize your music differently, you can organize them by folder structure, which might be what you want? It doesn't help with your last point though.

**Comment by kaysond** [comment]
Thanks I'll probably block access with the hosts file. My music is organized how I want. It's just an issue with lastfm's treatment of genre tags.

**Comment by kaysond** [comment]
But it would be nice to have it as an option. I don't think disabling the integration should affect the ID3 tags at all? The tag format is a standard, but the genres aren't. There's no reason airsonic needs to check the lastfm api for it.
