### ISSUE TITLE
Won't find albums with apostrophes

### ISSUE THREAD

**Issue by troykrahn** [airsonic/airsonic#780]
## Problem description

It seems my install of Airsonic does not like apostrophes in album or song names. If in an album name it won't appear at all in the library. If in the song name, it will appear separate from the list below the "Selected Songs" dropdown menu:
 
![screenshot_20180810_155409](https://user-images.githubusercontent.com/32440755/43975975-ac5d27ce-9cb5-11e8-856e-e956dad828a9.png)

Clicking on it just leads to another page with nothing to do: 

![screenshot_20180810_155959](https://user-images.githubusercontent.com/32440755/43976276-79262eae-9cb6-11e8-9395-60ed95ab5ba5.png)

The log will display something like this:

```2018-08-10 18:33:38.474  WARN --- o.airsonic.player.util.FileUtil          : Failed to list children for /opt/airsonic/music/Jet/Jet - Get Born/04 - Look What You???ve Done.flac```

### Steps to reproduce

1. Upload an album with an apostrophe in the name.
2. Re-scan the media folders.
3. Go back to Home, album is nowhere to be found.
4. Edit the album name to remove apostrophe and re-scan again.
5. Album appears normally.

**(These same steps apply to songs as well.)** 

## System information

 * **Airsonic version**: 10.1.2-RELEASE – July 28, 2018
 * **Operating system**: Apache Tomcat/8.5.23, java 1.8.0_181, Linux (203.9 MB / 630.0 MB)
 * **Proxy server**: None
 * **Client**: Firefox 61.0.2

**Comment by jooola** [comment]
It seems more like your file has some weird characters in the name. Try to rename the file, it might fix your problem. If not try to send the file over so we can test.

**Comment by reyjrar** [comment]
I am experiencing the same thing.  I also have tracks with apostrophes and international music as well.  Anything outside of ASCII seems to fail to index.

Is AirSonic UTF-8 safe?

FWIW: I've had no problems with SubSonic and MadSonic indexing these tracks/albums.

**Comment by 4oo4** [comment]
What database do you have? I can't remember if I had this problem when I originally used the built-in one, but I don't have this issue when using MySQL database (`utf8_general_ci` collation).

Do you have something like this this in your `/etc/tomcat8/server.xml`? Not sure if that was something I had to configure or was a default.
```
    <Connector port="8083" protocol="HTTP/1.1"
               connectionTimeout="20000"
               URIEncoding="UTF-8"
               redirectPort="8084" />
```

But yeah, Airsonic should be able to handle UTF-8 stuff as far as I can tell. 

![selection_003](https://user-images.githubusercontent.com/15698835/46706770-cb367480-cc25-11e8-98da-b0e8a462713f.png)

However, with MySQL I realize that I need to change my collation to utf8mb4 since they're [weird about Unicode](http://stackoverflow.com/questions/30074492/ddg#30074553). I'm also trying to figure out whether that was a default or not?

**Comment by xerg0n** [comment]
I can confirm this bug on version 
`10.2.1-RELEASE – February 18, 2019` 
with default settings running on 
`Apache Tomcat/8.0.50, java 1.8.0_192, FreeBSD (336.8 MB / 738.0 MB)`. 

I just started investigating, but it looks like (according to the `airsonic.script` file) that the files are added to the database correctly. 
I can find an enty looking like this
``INSERT INTO ARTIST VALUES(225,'Funny van Dannen','/mnt/[...]/Funny Van Dannen/Herzschei\u00dfe/Funny van Dannen - Falscher[...].mp3',12,'2019-03-05 01:06:20.000000000',TRUE,5)``
However as mentioned in the original report they do not get displayed if they contain non ascii characters. If they happen in the album name (e.g. `Herzscheiße`) the album does not get displayed. 
If they happen inside a song name the song they appear in a separate list as mentioned in the op.

**Comment by xerg0n** [comment]
I did some more research and have to retract my statement from earlier at least partly. For some reason it manages to read folder names (albums) properly and save them (like said above).
However it then simply cant access subfiles for this folder. 
Furthermore files with special characters like `- ä ü ß` are not accessable and show up like this in the database:
```
Real File:
/mnt/audio/Musik/newMusic/Funny van Dannen/Fischsuppe/01 Ergo‐Versicherungsgruppe.mp3 
Database Insert statement:
/mnt/audio/Musik/newMusic/Funny van Dannen/Fischsuppe/01 Ergo\ufffd\ufffd\ufffdVersicherungsgruppe.mp3 
```

**Comment by fxthomas** [comment]
I also use beets, and have a huge library with many different scripts (Japanese, Russian, Chinese). It's been working like this for ages without using asciify paths, so it's definitely possible to setup Airsonic this way.

That being said you're not alone in having encoding issues. Here are a few haphazard questions if you don't mind:

* What filesystem are you using? FAT32, NTFS, Ext4, something else?
* What's the encoding reported by Airsonic when you browse on a page? (look for the "Content-Type" header)
* What's the locale used by the Airsonic process (look for `LANG/LC_*` variables in `/proc/<pid of your Java process>/environ`)
* I don't see any special characters outside of ASCII in the "Real File" example you posted above, I assume that was intentional?
* On the other hand, `\ufffd` means that, when reading filenames, something tried to convert an invalid character from another encoding to Unicode and failed. These characters will appear as the "replacement character" (�). More on that below.
* This link appears like a good resource on the issue, can you also look at it: http://jonisalonen.com/2012/java-and-file-names-with-invalid-characters/

-----

The most common way for replacement characters to appear is that a process using the `C` locale (=ASCII only, on 7 bits) tries to convert a single-byte character from a superset (say, `latin-1`, on 8 bits) that contains characters above the 128 available to ASCII, like à, ç, ù,...

Example displaying this in Python:

```bash
$ python -c 'print(u"à".encode("latin-1").decode("latin-1", errors="replace"))'  # Latin-1 locale
à 
$ python -c 'print(u"à".encode("latin-1").decode("ascii", errors="replace"))'  # C locale
�
```

**Comment by IgniFerroque** [comment]
I think I might be having the same issue, so maybe my answers will help.

I'm storing the files on ZFS. I write the files from mac to an nfs mount with the nfc option set. Airsonic is running in an ubuntu container and reads the files on the nfs share.

Looking at the page source I see:
`<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">`

Looking in proc for the airsonic process I see:
`LANG=C`

The file I'm looking at contains `’` in the name. `ls` and `LC_CTYPE=C ls` both show the filename as:
`'02 (You'$'\342\200\231''re Better) Than Ever.flac'`

Maybe something in the airsonic.service file needs to set the locale for that process to utf8?

**Comment by IgniFerroque** [comment]
I updated the locale of the container from C to:

`root@airsonic:~# locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=`

Here's the process info:
`root@airsonic:~# cat /proc/$(pgrep -f airsonic)/environ | xargs -0 -L1 | grep LANG
LANG=en_US.UTF-8`

`ls` now shows the file as:
`'02 (You’re Better) Than Ever.flac'`

Airsonic still displays the same behavior with the the 3 diamond question mark blocks in the track name and it still won't play the track.

**Comment by IgniFerroque** [comment]
@fxthomas Do you have any thoughts on this?

**Comment by nelsongt** [comment]
Having this problem as well, using airsonic in a FreeNAS jail with SMB shares mounted in the jail. I haven't looked at any character encoding details yet.

**Comment by fxthomas** [comment]
I'm afraid I'm still not able to reproduce this, with Docker or standalone, and weird filenames have always worked fine for me on my server...

One thing I think we can do is add the locale information in the Airsonic info tab, so that it's easier to see when setting it up.

**Comment by nelsongt** [comment]
I may have fixed the problem, we'll see. I followed this [thread](https://www.ixsystems.com/community/threads/subsonic-character-problem-with-filenames.20208/) and added export LANG and LC_CTYPE variables to en_US.UTF-8 at the beginning of my tomcat9 service script, as well as adding those variables directly in front of the final jscv command at the end: `LC_ALL="en_US.UTF-8" LANG="en_US.UTF-8" run_rc_command "$1"`

I also added '-Dfile.encoding=UTF-8' to the jsvc command_args.

Now new files added to the database work correctly. But my old files are not working. I do not want to reset my database or alter any of my files. I thought that "clean-up database" followed by scan database would remove broken files and add them back in with fixed names, but this does not appear to be working. What is the best appraoch here? Temporarily move all problematic albums to another directory and then re-add them to my media folders?

**Comment by fxthomas** [comment]
Nice, glad to know you made it work!

* Can you check if `-Dfile.encoding.UTF-8` actually does something? Can you try removing it (I personally only have the `LC_ALL` bits somewhere on my system's locale configuration)?
* Re: scan, it's actually the opposite : "scan" marks files as non-present, which are then removed from the database by "clean-up". Your temporary move solution sounds like a good idea.
* Were you using your distribution's default Tomcat service? If so, can you share a patch between the two, or even better [contribute](https://github.com/airsonic/airsonic-docs/blob/master/install/war_tomcat.md) to the [distro-specific section in the documentation](https://airsonic.github.io/docs/install/war-tomcat/)?

**Comment by nelsongt** [comment]
Before, I changed many things before I realized only new database entries would be affected. I did a series of tests to confirm that all that was needed was 
`export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8`
at the beginning of the tomcat service script.

I found that the best approach to fixing the broken files was to search the database for files containing ufffd, add a '.' to the beginning of those files to hide them, rescan and clean database to remove broken entries, then remove the dot to unhide and rescan again to add properly.

Yes, I am using default service from the FreeBSD pkg repo. I can change the aisonic FreeBSD documentation, but I think this must be some kind of bug. My locale was always en_US.UTF-8. I think I should submit this issue to FreeBSD bugzilla and explain tomcat is not respecting set locale. What do you think?

**Comment by fxthomas** [comment]
I was going to say : yep, definitely send a bug report to the FreeBSD folks. Tomcat should follow the configured locale, but maybe there's a good reason why it isn't.

But then I googled, and apparently there's a [thread on the FreeBSD mailing list](https://lists.freebsd.org/pipermail/freebsd-ports/2017-December/111476.html) about Tomcat/Airsonic :wink: 

Can you let me know if the `rc.conf` changes they speak about works? I've never used FreeBSD and I haven't checked, but from the looks of it it does not modify service files installed by the package manager (so a little cleaner than your solution).

I'll add a new section to the docs warning about this specific issue.

**Comment by nelsongt** [comment]
Yes, that is the proper fix and it appears to be all that's needed to get unicode to work. I commented my lines out from the service script, added this to rc.conf: `tomcat9_env="LANG=en_US.UTF-8 TZ=America/New_York"`and adding new files with unicode chars to database works. I did not know this feature of FreeBSD rc.conf file before now and I consider myself above average user, *shrug*. This should be the fix for all using FreeBSD, but I don't think everyone with this problem has this particular OS/distro. Perhaps a similar approach in their respective distros is their solution.

Thanks for your help, was driving me crazy.

**Comment by fxthomas** [comment]
Nice, thank you too for all your work chasing that down!

I created a PR at https://github.com/airsonic/airsonic-docs/pull/82 so that the next people know about this. I have no way to test it, could you give it a quick read to make sure I did not get anything wrong?

**Comment by nelsongt** [comment]
Those instructions look right

**Comment by fxthomas** [comment]
I think this can be closed?

**Comment by hboetes** [comment]
I just ran into the same issue, after a lot of fidgeting around I figured out the environment of the app should contain the proper variables, in my case I had to add `LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8` to the tomcat startup script. After that I had to complete delete the database. There might be a more elegant solution to the latter.

**Comment by fxthomas** [comment]
@hboetes I think you were running OpenBSD right? Do the instructions [here](https://airsonic.github.io/docs/install/war-tomcat/#on-freebsd) for FreeBSD match what you needed to add?

**Comment by hboetes** [comment]
That solution put me on the tracks. But OpenBSD really is a world apart from FreeBSD.

**Comment by jwatte** [comment]
This happens for any file/directory with a Latin-1 file name for me, when using the Docker image.
I can't (easily) re-build the docker image to add the appropriate environment variables.

    Shell$ ls /var/fileserver/mp3/Tomas\ Blank\,\ Goteborgs\ Symfonietta\,\ solister/*
    'Tomas Blank, G'$'\224''teborgs Symfonietta, solister - V'$'\204''lkommen, du h'$'\204''rliga juletid - 01 - I Juletid.mp3'
    'Tomas Blank, G'$'\224''teborgs Symfonietta, solister - V'$'\204''lkommen, du h'$'\204''rliga juletid - 02 - Vi '$'\204''re musikanter.mp3'
    ...

Using Docker for Linux. Mounting the stored files (on ext4) into /airsonic/music using -v.

How can I use the docker image to run airsonic with these files?
I don't think you should close a bug that's clearly still happening, and doesn't have a good solution for all users.
