### ISSUE TITLE
dlna setting confusion

### ISSUE THREAD

**Issue by RuralHunter** [airsonic/airsonic#857]
I'm running the standalone version and my airsonic is running at http://192.168.166.37:8080/airsonic
I can see songs and play them in the web ui if I login. But I have problem with the dlna function. My dlna clients can see the songs but can not play them. There is nothing in the log. I don't know which setting prevent the other clients playing songs. Especially I don't understand the setting "LAN Server address". What's that? What value should I set it to in my case?

**Comment by RuralHunter** [comment]
I built and installed the latest snapshot and the problem is gone. But the qustion is still there about the setting: what is "LAN Server address" for? I just set it to same with the web ui address: http://192.168.166.37:8080/airsonic

**Comment by muff1nman** [comment]
This setting is for properly sending server generated urls back to the client such as for stream urls, cover art urls, etc. The reason why this setting exists is that in the DNLA code path, we cannot easily (or at least I'm not sure how) determine the correct base url to put in these generated urls especially when airsonic is sitting behind a proxy. For most other sections of the code, we can determine the base url based on the client HTTP request that was potentially modified by the proxy to give us the information we need without having people manually set it.

Hopefully that makes sense. In your case, setting it with a private ip works fine because that ip will be reachable on your LAN by your DNLA clients.
