### ISSUE TITLE
Max bitrate setting "No limit" is not accurate

### ISSUE THREAD

**Issue by RuralHunter** [airsonic/airsonic#867]
## Problem description

There is one option of max bitrate in the user setting page "No limit". I checked the source code and believe the actual meaning of it should be "Default". See the code starting here:
https://github.com/airsonic/airsonic/blob/adc224147a6266d729af8a5fa8d7f11f58598676/airsonic-main/src/main/java/org/airsonic/player/service/TranscodingService.java#L199

The value of option "No limit" is 0 which is TranscodeScheme.OFF. Then the actual bitrate will be set to a default value later here:
https://github.com/airsonic/airsonic/blob/adc224147a6266d729af8a5fa8d7f11f58598676/airsonic-main/src/main/java/org/airsonic/player/service/TranscodingService.java#L208

**Comment by eharris** [comment]
You are correct that if transcoding will be used on an audio file, then the code rather arbitrarily sets the output bitrate to 192kbps.  IMHO, this is wrong, as if the source is higher bitrate, then the transcoding will not maintain the same approximate quality, and if it is lower bitrate, then the transcoding will be wasting bitrate/bandwidth unnecessarily.

I'm working on submitting a PR that will fix this by using the same output bitrate as the input source unless it is over 320kbps, in which case it would set the limit to 320kbps (which can still be reduced by player/user settings).

Of course, different audio formats require somewhat different bitrates to achieve the same approximate level of quality, but trying to account for those differences would probably end up being overly complex.  And since there is kind of an implicit assumption that transcoding will most likely be used to render lossy formats, a 320k limit should preserve the max quality.  And if someone is doing transcoding to FLAC or some other non-lossy format, then they aren't really concerned with bitrate, and are probably not using the bitrate setting from Airsonic in their transcoding commands anyway.
