### ISSUE TITLE
Migration to Gitlab

### ISSUE THREAD

**Issue by jooola** [airsonic/airsonic#888]
Moving to Gitlab has already been mentioned in the community channel when Microsoft bought GitHub. Most of us agreed on it, but nothing has been done since then.

@heyarne suggested this migration again, because Giltab had some features not included in GitHub (I totally agree on this).

@airsonic/maintainers I would like a feedback from the main maintainers / contributors of the project so we all agree on this change.

@heyarne and I will start this process.

<details><summary>Task list</summary>
<p>

#### Creating the new organization on Gitlab
- [x] Create organization and repositories
- [ ] Grant current maintainers full access to the organization
- [ ] Import any organization key/password
    @muff1nman How should we do this ? Should we store the passwords into the organization vars used for CI/CD ?

#### Moving documentation repository
- [ ] Import repository using import tools && Set up Gitlab CI
- [ ] Move any GitHub specific files to Gitlab specific rules

#### Moving airsonic.github.io (=> airsonic.gitlab.io) repository
- [ ] Import repository using import tools && Set up Gitlab CI
- [ ] Move any GitHub specific files to Gitlab specific rules
- [ ] Bind airsonic.org to the gitlab page (@muff1nman I guess you has the ownership of this domain name)

#### Moving old subsonic repository
- [ ] Import repository using import tools
- [ ] Archive the project

#### Moving password repository
- [ ] Import repository using import tools
- [ ] Move any GitHub specific files to Gitlab specific rules
- [ ] Clean the project and move credentials to Gitlab variables (mostly used for CI/CD)

#### Moving airsonic-ui (angular project) repository
- [ ] Import repository using import tools && Set up Gitlab CI
- [ ] Move any GitHub specific files to Gitlab specific rules

#### Import heryane/airsonic-ui repository ?
- [ ] Import repository using import tools && Set up Gitlab CI
- [ ] Move any GitHub specific files to Gitlab specific rules

#### Moving homebrew-airsonic repository
- [ ] Import repository using import tools ?
- [ ] Or use Gitlab CI/CD to build tap (research needed ^^)

#### Moving airsonic repository
- [ ] Import repository using import tools
- [ ] Move any GitHub specific files to Gitlab specific rules
- [ ] Set up Gitlab CI
  - [ ] Testing
  - [ ] Building
  - [ ] Releasing
  - [ ] Docker
  - [ ] HomeBrew ?

####  Moving links and mirroring gitlab repos
- [ ] Add migration note everywhere
- [ ] Change any link to Gitlab
- [ ] Disable Issue Tracker && PR's on GitHub (Link them to gitlab)

</p>
</details>

Please report anything that I may have missed.

**Comment by heyarne** [comment]
In the matrix channel @muff1nman questioned why do this at all, and rightly so in my eyes so I figured I'd write a bit on the reasoning here.

1. Github has been bought by Microsoft a while ago. While for now they seem committed to keeping Github-the-platform mostly as is, it is uncertain if that will remain so.
2. Gitlab is a completely open source platform. You can host the source code management and continuous integration on your own servers.
3. Gitlab offers continuous integration. This means we could build and deploy the documentation and other things via Gitlab.

There are a couple of reasons to not migrate:
1. Again @muff1nman brought up what he called momentum. The Github repositories show some steady activity by now and we could easily lose this.
2. Everything that Gitlab does could be done on Github as well.

I'll go through each of these and add a few of my thoughts.

#### Bought by Microsoft
To be clear: Microsoft did make clear in the past that they act with corporate logic, which is not a surprise I guess. As soon as it shows that Github-of-today is not profitable for them anymore, they will find a way to get rid of it. For now the value in Github for Microsoft lies in owning *the* social network for open source software and that works for us, so this alone is no reason to rush.

#### Gitlab being open source
What can I say; I tried hosting it on my own server before (albeit without continuous integration) and it worked flawlessly. We have to be honest enough though to say that there currently are no airsonic community servers to host this on.

#### Gitlab offering CI
I'm a big fan. I had some (trivial) trouble in the past to set up jekyll for the airsonic docs and it would be incredibly nice for everyone to just fork them and build them with their own Gitlab account. As a positive side effect this could serve as build documentation.

#### Losing momentum
This is my biggest concern to be honest. It's become fairly common for people to just check for Github repositories and report issues there, or check for new releases etc. pp. It could be very confusing to introduce another similar-sounding platform. I don't have any numbers on this and I guess it's a question of how tech-savvy airsonic users are, but I'd place them on the more tech-savvy end. I would still say that Github is the platform for discovering open source projects, and being discovered is important for airsonic in many ways.

#### Building our own Gitlab on Github
While possible I don't know if this makes a lot of sense. I'm a big fan of small tools doing their job and doing it well (aka the unix way), but in a project such as this, this sometimes becomes brittle. Take for example continuous integration; a continuous integration platform widely used. It was just sold and they had to lay off some staff, and it's unclear what the path forward is for the VC firm that bought it. You could move on to the next hosted solution but there's a good chance you will face the same problem there in the foreseeable future. So instead you use some open source project, say https://drone.io/ – sounds lovely, but then you again have more knowledge about different accounts on different platforms to manage (plus the above-mentioned problem of still no community servers). In an organisation such as this one you should, in my eyes, try to manage as little information as possible, because less information can more easily be shared.

All in all I still vote for the migration. This of course does not mean shutting down everything at once; we need to be careful, but in my eyes it would be worth it.

**Comment by jvoisin** [comment]
The OpenMW project faced a similar dilemma, so it ended up with being on [gitlab]( https://gitlab.com/OpenMW/openmw ), with a replication on [github]( https://github.com/OpenMW/openmw ), allowing people to chose where they want to open a pull/merge request.

Gitlab allows mirroring by simply ticking a box somewhere in the options of the repository.

**Comment by jvoisin** [comment]
I've started to [migrate some stuff]( https://gitlab.com/airsonic/airsonic )

**Comment by tesshucom** [comment]
It seems like I forgot to close it.
Close it.
